// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (attachment_id, item_id, report_id, tenant_id, file_name, file_size, mime_type, s3_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING attachment_id, item_id, report_id, tenant_id, file_name, file_size, mime_type, s3_key, created_at, deleted_at
`

type CreateAttachmentParams struct {
	AttachmentID uuid.UUID `json:"attachment_id"`
	ItemID       uuid.UUID `json:"item_id"`
	ReportID     uuid.UUID `json:"report_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	FileName     string    `json:"file_name"`
	FileSize     int32     `json:"file_size"`
	MimeType     string    `json:"mime_type"`
	S3Key        string    `json:"s3_key"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.AttachmentID,
		arg.ItemID,
		arg.ReportID,
		arg.TenantID,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.S3Key,
	)
	var i Attachment
	err := row.Scan(
		&i.AttachmentID,
		&i.ItemID,
		&i.ReportID,
		&i.TenantID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.S3Key,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT attachment_id, item_id, report_id, tenant_id, file_name, file_size, mime_type, s3_key, created_at, deleted_at FROM attachments
WHERE tenant_id     = $1
  AND report_id     = $2
  AND item_id       = $3
  AND attachment_id = $4
  AND deleted_at    IS NULL
`

type GetAttachmentByIDParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ReportID     uuid.UUID `json:"report_id"`
	ItemID       uuid.UUID `json:"item_id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
}

func (q *Queries) GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID,
		arg.TenantID,
		arg.ReportID,
		arg.ItemID,
		arg.AttachmentID,
	)
	var i Attachment
	err := row.Scan(
		&i.AttachmentID,
		&i.ItemID,
		&i.ReportID,
		&i.TenantID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.S3Key,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachmentsByItemID = `-- name: ListAttachmentsByItemID :many
SELECT attachment_id, item_id, report_id, tenant_id, file_name, file_size, mime_type, s3_key, created_at, deleted_at FROM attachments
WHERE tenant_id  = $1
  AND report_id  = $2
  AND item_id    = $3
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListAttachmentsByItemIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
	ItemID   uuid.UUID `json:"item_id"`
}

func (q *Queries) ListAttachmentsByItemID(ctx context.Context, arg ListAttachmentsByItemIDParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByItemID, arg.TenantID, arg.ReportID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.AttachmentID,
			&i.ItemID,
			&i.ReportID,
			&i.TenantID,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.S3Key,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :exec
UPDATE attachments
SET deleted_at = now()
WHERE tenant_id     = $1
  AND report_id     = $2
  AND item_id       = $3
  AND attachment_id = $4
  AND deleted_at    IS NULL
`

type SoftDeleteAttachmentParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ReportID     uuid.UUID `json:"report_id"`
	ItemID       uuid.UUID `json:"item_id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
}

func (q *Queries) SoftDeleteAttachment(ctx context.Context, arg SoftDeleteAttachmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttachment,
		arg.TenantID,
		arg.ReportID,
		arg.ItemID,
		arg.AttachmentID,
	)
	return err
}

const softDeleteAttachmentsByItemID = `-- name: SoftDeleteAttachmentsByItemID :exec
UPDATE attachments
SET deleted_at = now()
WHERE tenant_id  = $1
  AND report_id  = $2
  AND item_id    = $3
  AND deleted_at IS NULL
`

type SoftDeleteAttachmentsByItemIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
	ItemID   uuid.UUID `json:"item_id"`
}

func (q *Queries) SoftDeleteAttachmentsByItemID(ctx context.Context, arg SoftDeleteAttachmentsByItemIDParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttachmentsByItemID, arg.TenantID, arg.ReportID, arg.ItemID)
	return err
}

const softDeleteAttachmentsByReportID = `-- name: SoftDeleteAttachmentsByReportID :exec
UPDATE attachments
SET deleted_at = now()
WHERE tenant_id  = $1
  AND report_id  = $2
  AND deleted_at IS NULL
`

type SoftDeleteAttachmentsByReportIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) SoftDeleteAttachmentsByReportID(ctx context.Context, arg SoftDeleteAttachmentsByReportIDParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttachmentsByReportID, arg.TenantID, arg.ReportID)
	return err
}
