// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT category_id, tenant_id, code, name_ja, sort_order, is_active, created_at, updated_at FROM categories
WHERE category_id = $1
  AND is_active = true
  AND (tenant_id = $2 OR tenant_id IS NULL)
`

type GetCategoryByIDParams struct {
	CategoryID uuid.UUID   `json:"category_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.CategoryID, arg.TenantID)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.TenantID,
		&i.Code,
		&i.NameJa,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT category_id, tenant_id, code, name_ja, sort_order, is_active, created_at, updated_at FROM categories
WHERE is_active = true
  AND (tenant_id IS NULL OR tenant_id = $1)
ORDER BY sort_order ASC
`

func (q *Queries) ListActiveCategories(ctx context.Context, tenantID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listActiveCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.TenantID,
			&i.Code,
			&i.NameJa,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
