// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_reports.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMyReportsByStatus = `-- name: CountMyReportsByStatus :many
SELECT status, COUNT(*)::int AS count
FROM expense_reports
WHERE tenant_id  = $1
  AND user_id    = $2
  AND deleted_at IS NULL
GROUP BY status
`

type CountMyReportsByStatusParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type CountMyReportsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountMyReportsByStatus(ctx context.Context, arg CountMyReportsByStatusParams) ([]CountMyReportsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countMyReportsByStatus, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMyReportsByStatusRow{}
	for rows.Next() {
		var i CountMyReportsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countReportsByStatus = `-- name: CountReportsByStatus :many
SELECT status, COUNT(*)::int AS count
FROM expense_reports
WHERE tenant_id  = $1
  AND deleted_at IS NULL
GROUP BY status
`

type CountReportsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountReportsByStatus(ctx context.Context, tenantID uuid.UUID) ([]CountReportsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countReportsByStatus, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountReportsByStatusRow{}
	for rows.Next() {
		var i CountReportsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReport = `-- name: CreateReport :one
INSERT INTO expense_reports (tenant_id, user_id, title, period_start, period_end, reference_report_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING report_id, tenant_id, user_id, title, period_start, period_end, status, total_amount, reference_report_id, submitted_by, submitted_at, approved_by, approved_at, approval_comment, rejected_by, rejected_at, rejection_reason, paid_by, paid_at, created_at, updated_at, deleted_at
`

type CreateReportParams struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Title             string      `json:"title"`
	PeriodStart       pgtype.Date `json:"period_start"`
	PeriodEnd         pgtype.Date `json:"period_end"`
	ReferenceReportID pgtype.UUID `json:"reference_report_id"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.TenantID,
		arg.UserID,
		arg.Title,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ReferenceReportID,
	)
	var i ExpenseReport
	err := row.Scan(
		&i.ReportID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.TotalAmount,
		&i.ReferenceReportID,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalComment,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.PaidBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT report_id, tenant_id, user_id, title, period_start, period_end, status, total_amount, reference_report_id, submitted_by, submitted_at, approved_by, approved_at, approval_comment, rejected_by, rejected_at, rejection_reason, paid_by, paid_at, created_at, updated_at, deleted_at FROM expense_reports
WHERE tenant_id  = $1
  AND report_id  = $2
  AND deleted_at IS NULL
`

type GetReportByIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) GetReportByID(ctx context.Context, arg GetReportByIDParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, getReportByID, arg.TenantID, arg.ReportID)
	var i ExpenseReport
	err := row.Scan(
		&i.ReportID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.TotalAmount,
		&i.ReferenceReportID,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalComment,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.PaidBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllReports = `-- name: ListAllReports :many
SELECT report_id, tenant_id, user_id, title, period_start, period_end, status, total_amount, reference_report_id, submitted_by, submitted_at, approved_by, approved_at, approval_comment, rejected_by, rejected_at, rejection_reason, paid_by, paid_at, created_at, updated_at, deleted_at FROM expense_reports
WHERE tenant_id  = $1
  AND deleted_at IS NULL
  AND ($3::text IS NULL OR status = $3)
  AND ($4::date IS NULL OR period_start >= $4)
  AND ($5::date IS NULL OR period_end <= $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
  AND ($7::uuid IS NULL OR user_id = $7)
ORDER BY created_at DESC
LIMIT $2
`

type ListAllReportsParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	Limit    int32              `json:"limit"`
	Status   pgtype.Text        `json:"status"`
	FromDate pgtype.Date        `json:"from_date"`
	ToDate   pgtype.Date        `json:"to_date"`
	Cursor   pgtype.Timestamptz `json:"cursor"`
	UserID   pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ListAllReports(ctx context.Context, arg ListAllReportsParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listAllReports,
		arg.TenantID,
		arg.Limit,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
		arg.Cursor,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ReportID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.TotalAmount,
			&i.ReferenceReportID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApprovalComment,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.PaidBy,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayableReports = `-- name: ListPayableReports :many
SELECT er.report_id, er.tenant_id, er.user_id, er.title, er.period_start, er.period_end, er.status, er.total_amount, er.reference_report_id, er.submitted_by, er.submitted_at, er.approved_by, er.approved_at, er.approval_comment, er.rejected_by, er.rejected_at, er.rejection_reason, er.paid_by, er.paid_at, er.created_at, er.updated_at, er.deleted_at
FROM expense_reports er
JOIN users u ON er.user_id = u.id
WHERE er.tenant_id  = $1
  AND er.status     = 'approved'
  AND er.deleted_at IS NULL
  AND ($3::text IS NULL OR u.name ILIKE '%' || $3 || '%')
  AND ($4::timestamptz IS NULL OR er.approved_at < $4)
ORDER BY er.approved_at DESC
LIMIT $2
`

type ListPayableReportsParams struct {
	TenantID      uuid.UUID          `json:"tenant_id"`
	Limit         int32              `json:"limit"`
	ApplicantName pgtype.Text        `json:"applicant_name"`
	Cursor        pgtype.Timestamptz `json:"cursor"`
}

func (q *Queries) ListPayableReports(ctx context.Context, arg ListPayableReportsParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listPayableReports,
		arg.TenantID,
		arg.Limit,
		arg.ApplicantName,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ReportID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.TotalAmount,
			&i.ReferenceReportID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApprovalComment,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.PaidBy,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReports = `-- name: ListPendingReports :many
SELECT er.report_id, er.tenant_id, er.user_id, er.title, er.period_start, er.period_end, er.status, er.total_amount, er.reference_report_id, er.submitted_by, er.submitted_at, er.approved_by, er.approved_at, er.approval_comment, er.rejected_by, er.rejected_at, er.rejection_reason, er.paid_by, er.paid_at, er.created_at, er.updated_at, er.deleted_at
FROM expense_reports er
JOIN users u ON er.user_id = u.id
WHERE er.tenant_id  = $1
  AND er.status     = 'submitted'
  AND er.deleted_at IS NULL
  AND ($3::text IS NULL OR u.name ILIKE '%' || $3 || '%')
  AND ($4::timestamptz IS NULL OR er.submitted_at < $4)
ORDER BY er.submitted_at DESC
LIMIT $2
`

type ListPendingReportsParams struct {
	TenantID      uuid.UUID          `json:"tenant_id"`
	Limit         int32              `json:"limit"`
	ApplicantName pgtype.Text        `json:"applicant_name"`
	Cursor        pgtype.Timestamptz `json:"cursor"`
}

func (q *Queries) ListPendingReports(ctx context.Context, arg ListPendingReportsParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listPendingReports,
		arg.TenantID,
		arg.Limit,
		arg.ApplicantName,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ReportID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.TotalAmount,
			&i.ReferenceReportID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApprovalComment,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.PaidBy,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReports = `-- name: ListRecentReports :many
SELECT report_id, tenant_id, user_id, title, period_start, period_end, status, total_amount, reference_report_id, submitted_by, submitted_at, approved_by, approved_at, approval_comment, rejected_by, rejected_at, rejection_reason, paid_by, paid_at, created_at, updated_at, deleted_at FROM expense_reports
WHERE tenant_id  = $1
  AND user_id    = $2
  AND deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT $3
`

type ListRecentReportsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListRecentReports(ctx context.Context, arg ListRecentReportsParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listRecentReports, arg.TenantID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ReportID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.TotalAmount,
			&i.ReferenceReportID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApprovalComment,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.PaidBy,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByUser = `-- name: ListReportsByUser :many
SELECT report_id, tenant_id, user_id, title, period_start, period_end, status, total_amount, reference_report_id, submitted_by, submitted_at, approved_by, approved_at, approval_comment, rejected_by, rejected_at, rejection_reason, paid_by, paid_at, created_at, updated_at, deleted_at FROM expense_reports
WHERE tenant_id = $1
  AND user_id   = $2
  AND deleted_at IS NULL
  AND ($4::text IS NULL OR status = $4)
  AND ($5::date IS NULL OR period_start >= $5)
  AND ($6::date IS NULL OR period_end <= $6)
  AND ($7::timestamptz IS NULL OR created_at < $7)
ORDER BY created_at DESC
LIMIT $3
`

type ListReportsByUserParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	UserID   uuid.UUID          `json:"user_id"`
	Limit    int32              `json:"limit"`
	Status   pgtype.Text        `json:"status"`
	FromDate pgtype.Date        `json:"from_date"`
	ToDate   pgtype.Date        `json:"to_date"`
	Cursor   pgtype.Timestamptz `json:"cursor"`
}

func (q *Queries) ListReportsByUser(ctx context.Context, arg ListReportsByUserParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listReportsByUser,
		arg.TenantID,
		arg.UserID,
		arg.Limit,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ReportID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.TotalAmount,
			&i.ReferenceReportID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApprovalComment,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.PaidBy,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlySummaryAll = `-- name: MonthlySummaryAll :many
SELECT to_char(date_trunc('month', submitted_at), 'YYYY-MM') AS year_month,
       SUM(total_amount)::int                                 AS total_amount
FROM expense_reports
WHERE tenant_id   = $1
  AND status      IN ('approved', 'paid')
  AND deleted_at  IS NULL
  AND submitted_at >= date_trunc('month', now()) - ($2::int - 1) * INTERVAL '1 month'
GROUP BY date_trunc('month', submitted_at)
ORDER BY date_trunc('month', submitted_at) DESC
`

type MonthlySummaryAllParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  int32     `json:"column_2"`
}

type MonthlySummaryAllRow struct {
	YearMonth   string `json:"year_month"`
	TotalAmount int32  `json:"total_amount"`
}

func (q *Queries) MonthlySummaryAll(ctx context.Context, arg MonthlySummaryAllParams) ([]MonthlySummaryAllRow, error) {
	rows, err := q.db.Query(ctx, monthlySummaryAll, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlySummaryAllRow{}
	for rows.Next() {
		var i MonthlySummaryAllRow
		if err := rows.Scan(&i.YearMonth, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlySummaryByUser = `-- name: MonthlySummaryByUser :many
SELECT to_char(date_trunc('month', submitted_at), 'YYYY-MM') AS year_month,
       SUM(total_amount)::int                                 AS total_amount
FROM expense_reports
WHERE tenant_id   = $1
  AND user_id     = $2
  AND status      IN ('approved', 'paid')
  AND deleted_at  IS NULL
  AND submitted_at >= date_trunc('month', now()) - ($3::int - 1) * INTERVAL '1 month'
GROUP BY date_trunc('month', submitted_at)
ORDER BY date_trunc('month', submitted_at) DESC
`

type MonthlySummaryByUserParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Column3  int32     `json:"column_3"`
}

type MonthlySummaryByUserRow struct {
	YearMonth   string `json:"year_month"`
	TotalAmount int32  `json:"total_amount"`
}

func (q *Queries) MonthlySummaryByUser(ctx context.Context, arg MonthlySummaryByUserParams) ([]MonthlySummaryByUserRow, error) {
	rows, err := q.db.Query(ctx, monthlySummaryByUser, arg.TenantID, arg.UserID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlySummaryByUserRow{}
	for rows.Next() {
		var i MonthlySummaryByUserRow
		if err := rows.Scan(&i.YearMonth, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteReport = `-- name: SoftDeleteReport :exec
UPDATE expense_reports
SET deleted_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND report_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteReportParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) SoftDeleteReport(ctx context.Context, arg SoftDeleteReportParams) error {
	_, err := q.db.Exec(ctx, softDeleteReport, arg.TenantID, arg.ReportID)
	return err
}

const updateReport = `-- name: UpdateReport :one
UPDATE expense_reports
SET title        = $3,
    period_start = $4,
    period_end   = $5,
    updated_at   = now()
WHERE tenant_id  = $1
  AND report_id  = $2
  AND deleted_at IS NULL
  AND updated_at = $6
RETURNING report_id, tenant_id, user_id, title, period_start, period_end, status, total_amount, reference_report_id, submitted_by, submitted_at, approved_by, approved_at, approval_comment, rejected_by, rejected_at, rejection_reason, paid_by, paid_at, created_at, updated_at, deleted_at
`

type UpdateReportParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ReportID    uuid.UUID   `json:"report_id"`
	Title       string      `json:"title"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, updateReport,
		arg.TenantID,
		arg.ReportID,
		arg.Title,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.UpdatedAt,
	)
	var i ExpenseReport
	err := row.Scan(
		&i.ReportID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.TotalAmount,
		&i.ReferenceReportID,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalComment,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.PaidBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE expense_reports
SET status           = $3,
    submitted_by     = $4,
    submitted_at     = $5,
    approved_by      = $6,
    approved_at      = $7,
    approval_comment = $8,
    rejected_by      = $9,
    rejected_at      = $10,
    rejection_reason = $11,
    paid_by          = $12,
    paid_at          = $13,
    updated_at       = now()
WHERE tenant_id  = $1
  AND report_id  = $2
  AND deleted_at IS NULL
  AND updated_at = $14
RETURNING report_id, tenant_id, user_id, title, period_start, period_end, status, total_amount, reference_report_id, submitted_by, submitted_at, approved_by, approved_at, approval_comment, rejected_by, rejected_at, rejection_reason, paid_by, paid_at, created_at, updated_at, deleted_at
`

type UpdateReportStatusParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	ReportID        uuid.UUID          `json:"report_id"`
	Status          string             `json:"status"`
	SubmittedBy     pgtype.UUID        `json:"submitted_by"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	ApprovalComment pgtype.Text        `json:"approval_comment"`
	RejectedBy      pgtype.UUID        `json:"rejected_by"`
	RejectedAt      pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	PaidBy          pgtype.UUID        `json:"paid_by"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, updateReportStatus,
		arg.TenantID,
		arg.ReportID,
		arg.Status,
		arg.SubmittedBy,
		arg.SubmittedAt,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.ApprovalComment,
		arg.RejectedBy,
		arg.RejectedAt,
		arg.RejectionReason,
		arg.PaidBy,
		arg.PaidAt,
		arg.UpdatedAt,
	)
	var i ExpenseReport
	err := row.Scan(
		&i.ReportID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.TotalAmount,
		&i.ReferenceReportID,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApprovalComment,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.PaidBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateReportTotalAmount = `-- name: UpdateReportTotalAmount :exec
UPDATE expense_reports
SET total_amount = (
    SELECT COALESCE(SUM(ei.amount), 0)
    FROM expense_items ei
    WHERE ei.report_id  = expense_reports.report_id
      AND ei.tenant_id  = expense_reports.tenant_id
      AND ei.deleted_at IS NULL
),
    updated_at = now()
WHERE expense_reports.tenant_id = $1
  AND expense_reports.report_id = $2
`

type UpdateReportTotalAmountParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) UpdateReportTotalAmount(ctx context.Context, arg UpdateReportTotalAmountParams) error {
	_, err := q.db.Exec(ctx, updateReportTotalAmount, arg.TenantID, arg.ReportID)
	return err
}
