// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_items.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExpenseItemsByReportID = `-- name: CountExpenseItemsByReportID :one
SELECT COUNT(*)::int AS count
FROM expense_items
WHERE tenant_id  = $1
  AND report_id  = $2
  AND deleted_at IS NULL
`

type CountExpenseItemsByReportIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) CountExpenseItemsByReportID(ctx context.Context, arg CountExpenseItemsByReportIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, countExpenseItemsByReportID, arg.TenantID, arg.ReportID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createExpenseItem = `-- name: CreateExpenseItem :one
INSERT INTO expense_items (report_id, tenant_id, expense_date, amount, category_id, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING item_id, report_id, tenant_id, expense_date, amount, category_id, description, created_at, updated_at, deleted_at
`

type CreateExpenseItemParams struct {
	ReportID    uuid.UUID   `json:"report_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	ExpenseDate pgtype.Date `json:"expense_date"`
	Amount      int32       `json:"amount"`
	CategoryID  uuid.UUID   `json:"category_id"`
	Description string      `json:"description"`
}

func (q *Queries) CreateExpenseItem(ctx context.Context, arg CreateExpenseItemParams) (ExpenseItem, error) {
	row := q.db.QueryRow(ctx, createExpenseItem,
		arg.ReportID,
		arg.TenantID,
		arg.ExpenseDate,
		arg.Amount,
		arg.CategoryID,
		arg.Description,
	)
	var i ExpenseItem
	err := row.Scan(
		&i.ItemID,
		&i.ReportID,
		&i.TenantID,
		&i.ExpenseDate,
		&i.Amount,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenseItemByID = `-- name: GetExpenseItemByID :one
SELECT item_id, report_id, tenant_id, expense_date, amount, category_id, description, created_at, updated_at, deleted_at FROM expense_items
WHERE tenant_id  = $1
  AND report_id  = $2
  AND item_id    = $3
  AND deleted_at IS NULL
`

type GetExpenseItemByIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
	ItemID   uuid.UUID `json:"item_id"`
}

func (q *Queries) GetExpenseItemByID(ctx context.Context, arg GetExpenseItemByIDParams) (ExpenseItem, error) {
	row := q.db.QueryRow(ctx, getExpenseItemByID, arg.TenantID, arg.ReportID, arg.ItemID)
	var i ExpenseItem
	err := row.Scan(
		&i.ItemID,
		&i.ReportID,
		&i.TenantID,
		&i.ExpenseDate,
		&i.Amount,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpenseItemsByReportID = `-- name: ListExpenseItemsByReportID :many
SELECT item_id, report_id, tenant_id, expense_date, amount, category_id, description, created_at, updated_at, deleted_at FROM expense_items
WHERE tenant_id  = $1
  AND report_id  = $2
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListExpenseItemsByReportIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) ListExpenseItemsByReportID(ctx context.Context, arg ListExpenseItemsByReportIDParams) ([]ExpenseItem, error) {
	rows, err := q.db.Query(ctx, listExpenseItemsByReportID, arg.TenantID, arg.ReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseItem{}
	for rows.Next() {
		var i ExpenseItem
		if err := rows.Scan(
			&i.ItemID,
			&i.ReportID,
			&i.TenantID,
			&i.ExpenseDate,
			&i.Amount,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpenseItem = `-- name: SoftDeleteExpenseItem :exec
UPDATE expense_items
SET deleted_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND report_id = $2
  AND item_id   = $3
  AND deleted_at IS NULL
`

type SoftDeleteExpenseItemParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
	ItemID   uuid.UUID `json:"item_id"`
}

func (q *Queries) SoftDeleteExpenseItem(ctx context.Context, arg SoftDeleteExpenseItemParams) error {
	_, err := q.db.Exec(ctx, softDeleteExpenseItem, arg.TenantID, arg.ReportID, arg.ItemID)
	return err
}

const softDeleteExpenseItemsByReportID = `-- name: SoftDeleteExpenseItemsByReportID :exec
UPDATE expense_items
SET deleted_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND report_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteExpenseItemsByReportIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) SoftDeleteExpenseItemsByReportID(ctx context.Context, arg SoftDeleteExpenseItemsByReportIDParams) error {
	_, err := q.db.Exec(ctx, softDeleteExpenseItemsByReportID, arg.TenantID, arg.ReportID)
	return err
}

const updateExpenseItem = `-- name: UpdateExpenseItem :one
UPDATE expense_items
SET expense_date = $4,
    amount       = $5,
    category_id  = $6,
    description  = $7,
    updated_at   = now()
WHERE tenant_id  = $1
  AND report_id  = $2
  AND item_id    = $3
  AND deleted_at IS NULL
  AND updated_at = $8
RETURNING item_id, report_id, tenant_id, expense_date, amount, category_id, description, created_at, updated_at, deleted_at
`

type UpdateExpenseItemParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ReportID    uuid.UUID   `json:"report_id"`
	ItemID      uuid.UUID   `json:"item_id"`
	ExpenseDate pgtype.Date `json:"expense_date"`
	Amount      int32       `json:"amount"`
	CategoryID  uuid.UUID   `json:"category_id"`
	Description string      `json:"description"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateExpenseItem(ctx context.Context, arg UpdateExpenseItemParams) (ExpenseItem, error) {
	row := q.db.QueryRow(ctx, updateExpenseItem,
		arg.TenantID,
		arg.ReportID,
		arg.ItemID,
		arg.ExpenseDate,
		arg.Amount,
		arg.CategoryID,
		arg.Description,
		arg.UpdatedAt,
	)
	var i ExpenseItem
	err := row.Scan(
		&i.ItemID,
		&i.ReportID,
		&i.TenantID,
		&i.ExpenseDate,
		&i.Amount,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
