// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	AttachmentID uuid.UUID          `json:"attachment_id"`
	ItemID       uuid.UUID          `json:"item_id"`
	ReportID     uuid.UUID          `json:"report_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	FileName     string             `json:"file_name"`
	FileSize     int32              `json:"file_size"`
	MimeType     string             `json:"mime_type"`
	S3Key        string             `json:"s3_key"`
	CreatedAt    time.Time          `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Category struct {
	CategoryID uuid.UUID   `json:"category_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	Code       string      `json:"code"`
	NameJa     string      `json:"name_ja"`
	SortOrder  int32       `json:"sort_order"`
	IsActive   bool        `json:"is_active"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type ExpenseItem struct {
	ItemID      uuid.UUID          `json:"item_id"`
	ReportID    uuid.UUID          `json:"report_id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	Amount      int32              `json:"amount"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Description string             `json:"description"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ExpenseReport struct {
	ReportID          uuid.UUID          `json:"report_id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	UserID            uuid.UUID          `json:"user_id"`
	Title             string             `json:"title"`
	PeriodStart       pgtype.Date        `json:"period_start"`
	PeriodEnd         pgtype.Date        `json:"period_end"`
	Status            string             `json:"status"`
	TotalAmount       int32              `json:"total_amount"`
	ReferenceReportID pgtype.UUID        `json:"reference_report_id"`
	SubmittedBy       pgtype.UUID        `json:"submitted_by"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ApprovedBy        pgtype.UUID        `json:"approved_by"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
	ApprovalComment   pgtype.Text        `json:"approval_comment"`
	RejectedBy        pgtype.UUID        `json:"rejected_by"`
	RejectedAt        pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason   pgtype.Text        `json:"rejection_reason"`
	PaidBy            pgtype.UUID        `json:"paid_by"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type RefreshToken struct {
	Jti       uuid.UUID `json:"jti"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	IsRevoked bool      `json:"is_revoked"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Tenant struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CompanyName string    `json:"company_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TenantMembership struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
