// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (jti, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING jti, user_id, token_hash, is_revoked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	Jti       uuid.UUID `json:"jti"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.Jti,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.TokenHash,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByJTI = `-- name: GetRefreshTokenByJTI :one
SELECT jti, user_id, token_hash, is_revoked, expires_at, created_at FROM refresh_tokens
WHERE jti = $1
`

func (q *Queries) GetRefreshTokenByJTI(ctx context.Context, jti uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByJTI, jti)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.TokenHash,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET is_revoked = true
WHERE jti = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, jti uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, jti)
	return err
}
