// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (company_name)
VALUES ($1)
RETURNING tenant_id, company_name, created_at, updated_at
`

func (q *Queries) CreateTenant(ctx context.Context, companyName string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, companyName)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.CompanyName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT tenant_id, company_name, created_at, updated_at FROM tenants
WHERE tenant_id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, tenantID uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.CompanyName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
