// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_memberships.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO tenant_memberships (tenant_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING tenant_id, user_id, role, created_at, updated_at
`

type CreateMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByUserID = `-- name: GetMembershipByUserID :one
SELECT tenant_id, user_id, role, created_at, updated_at FROM tenant_memberships
WHERE user_id = $1
`

func (q *Queries) GetMembershipByUserID(ctx context.Context, userID uuid.UUID) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, userID)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasApprover = `-- name: HasApprover :one
SELECT EXISTS(
    SELECT 1 FROM tenant_memberships
    WHERE tenant_id = $1
      AND role = 'approver'
) AS has_approver
`

func (q *Queries) HasApprover(ctx context.Context, tenantID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasApprover, tenantID)
	var has_approver bool
	err := row.Scan(&has_approver)
	return has_approver, err
}

const countMembersByTenantID = `-- name: CountMembersByTenantID :one
SELECT COUNT(*)::int FROM tenant_memberships WHERE tenant_id = $1
`

// CountMembersByTenantID はテナント内のメンバー総数を返す。
// db/queries/tenant_memberships.sql の CountMembersByTenantID クエリに対応する。
// sqlc generate で再生成予定。
func (q *Queries) CountMembersByTenantID(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMembersByTenantID, tenantID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const listMembershipsByTenantID = `-- name: ListMembershipsByTenantID :many
SELECT tenant_id, user_id, role, created_at, updated_at FROM tenant_memberships
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMembershipsByTenantID(ctx context.Context, tenantID uuid.UUID) ([]TenantMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantMembership{}
	for rows.Next() {
		var i TenantMembership
		if err := rows.Scan(
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
