/**
 * 添付ファイル操作の成功トースト文言（add / edit 両モード共通）。
 * state-management.md §6.5.5「添付ファイル成功トーストの発火条件」に準拠する。
 * add モード固有の文言は使用しない（案 A: UI 一貫性優先、issue #143）。
 */
export const ATTACHMENT_UPLOAD_SUCCESS = 'ファイルをアップロードしました';
export const ATTACHMENT_DELETE_SUCCESS = '添付ファイルを削除しました';

export const ERROR_CODES = {
  // 400 不正リクエスト
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  // 401 認証エラー
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  // 403 権限エラー
  FORBIDDEN: 'FORBIDDEN',
  SELF_APPROVAL_NOT_ALLOWED: 'SELF_APPROVAL_NOT_ALLOWED',
  SELF_PAYMENT_NOT_ALLOWED: 'SELF_PAYMENT_NOT_ALLOWED',
  // 404 リソース未検出
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  // 409 競合
  CONFLICT: 'CONFLICT',
  // 413 ファイルサイズ超過
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  // 422 業務ルール違反
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  REPORT_NOT_EDITABLE: 'REPORT_NOT_EDITABLE',
  REPORT_NOT_DELETABLE: 'REPORT_NOT_DELETABLE',
  EMPTY_REPORT_SUBMISSION: 'EMPTY_REPORT_SUBMISSION',
  NO_APPROVER_IN_TENANT: 'NO_APPROVER_IN_TENANT',
  INVALID_PERIOD: 'INVALID_PERIOD',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  MISSING_REJECTION_REASON: 'MISSING_REJECTION_REASON',
  // 429 レート制限超過
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  // 500 サーバー内部エラー
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
